document.querySelector(".one").addEventListener("click",function(){
  console.log("one");
},true);
document.querySelector(".two").addEventListener("click",function(){
  console.log("two");
},true);
document.querySelector(".three").addEventListener("click",function(){
  console.log("three");
},true);